### ISSUE TITLE
requirement.txt

### ISSUE THREAD

**Issue by hlsafin** [qgallouedec/lge#11]
i've been having a difficult time recreating or even running similar experiments on atari environment. if anyone has got it this to work, can you please provide versions for  the following packages:
Python 
Stable_baselines3 
gym 
pytorch
numpy

If it's not so much to ask
thank you

**Comment by qgallouedec** [comment]
hey, just pip install the package

```
cd lge
pip install .
```

**Comment by hlsafin** [comment]
yes, this didn't work for me.
