### ISSUE TITLE
the question about the exploration strategy in code

### ISSUE THREAD

**Issue by jgp-github** [qgallouedec/lge#6]
hi, when I try to understand the code of explore_lge_maze.py in LGE-MAIN, I have a question about the exploration strategy after returning the last goal. 
        In my understanding, the goal-conditioned policy  is used as the exploration strategy after returning in the code,  but the random exploration strategy is encouraged to uesed in the paper. Do I understand correctly?  Looking forward to your help, thanks.

**Comment by qgallouedec** [comment]
The exploration strategy after the agent has reached the final goal is indeed random with the action consistency trick. For this, the step function returns an info dict containing the action to be repeated:

https://github.com/qgallouedec/lge/blob/ae7fb4a526649c474d242e9f527d13dc3d876752/lge/lge.py#L111-L114

When this dict is passed, the action is random in 10% of cases, and equal to the previous action in 90%.

**Comment by jgp-github** [comment]
Thanks for your answer. And, which policy is used to select action in 10% of cases, the goal-conditioned policy or the random policy which select action from env.action_space randomly?

**Comment by qgallouedec** [comment]
In the initial version of LGE, the agent samples uniformly in the action space.
However, digging into the implementation, I realize that the agent actually selects an action by pursuing the last goal (which intuitively is a bit counterproductive). This is an error. Thanks for participating to notice it ;-)
The good news is that by correcting it, the agent explores even more efficiently. It takes 40k less (40% then) timesteps to achieve 95% space coverage! Look at the result (maze, orange is old, blue is new):
![Figure_1](https://user-images.githubusercontent.com/45557362/198693046-d42d5dd6-2b5c-445b-af4c-e8ac728f0f3d.png)

**Comment by jgp-github** [comment]
Ok, that's good, thanks for your answer.
